export interface Surah {
  number: number;
  name: string;
  transliteration: string;
  verses: number;
  pages: number;
  juz: number;
}

export interface Juz {
  number: number;
  startSurah: number;
  endSurah: number;
}

export const JUZS: Juz[] = [
  { number: 1, startSurah: 1, endSurah: 2 },
  { number: 2, startSurah: 2, endSurah: 2 },
  { number: 3, startSurah: 2, endSurah: 3 },
  { number: 4, startSurah: 3, endSurah: 4 },
  { number: 5, startSurah: 4, endSurah: 4 },
  { number: 6, startSurah: 4, endSurah: 5 },
  { number: 7, startSurah: 5, endSurah: 6 },
  { number: 8, startSurah: 6, endSurah: 7 },
  { number: 9, startSurah: 7, endSurah: 8 },
  { number: 10, startSurah: 8, endSurah: 9 },
  { number: 11, startSurah: 9, endSurah: 11 },
  { number: 12, startSurah: 11, endSurah: 12 },
  { number: 13, startSurah: 12, endSurah: 14 },
  { number: 14, startSurah: 15, endSurah: 16 },
  { number: 15, startSurah: 17, endSurah: 18 },
  { number: 16, startSurah: 18, endSurah: 20 },
  { number: 17, startSurah: 20, endSurah: 22 },
  { number: 18, startSurah: 23, endSurah: 25 },
  { number: 19, startSurah: 25, endSurah: 27 },
  { number: 20, startSurah: 27, endSurah: 29 },
  { number: 21, startSurah: 29, endSurah: 33 },
  { number: 22, startSurah: 33, endSurah: 36 },
  { number: 23, startSurah: 36, endSurah: 39 },
  { number: 24, startSurah: 39, endSurah: 41 },
  { number: 25, startSurah: 41, endSurah: 45 },
  { number: 26, startSurah: 46, endSurah: 51 },
  { number: 27, startSurah: 51, endSurah: 57 },
  { number: 28, startSurah: 58, endSurah: 66 },
  { number: 29, startSurah: 67, endSurah: 77 },
  { number: 30, startSurah: 78, endSurah: 114 },
];

// Helper: Juz mapping for each surah (first juz that contains any part of the surah)
const surahToJuz: { [key: number]: number } = {};
JUZS.forEach(juz => {
  for (let s = juz.startSurah; s <= juz.endSurah; s++) {
    if (!surahToJuz[s]) surahToJuz[s] = juz.number;
  }
});

export const SURAHS: Surah[] = [
  { number: 1, name: "الفاتحة", transliteration: "Al-Fatiha", verses: 7, pages: 1, juz: surahToJuz[1] },
  { number: 2, name: "البقرة", transliteration: "Al-Baqarah", verses: 286, pages: 48, juz: surahToJuz[2] },
  { number: 3, name: "آل عمران", transliteration: "Ali 'Imran", verses: 200, pages: 20, juz: surahToJuz[3] },
  { number: 4, name: "النساء", transliteration: "An-Nisa", verses: 176, pages: 24, juz: surahToJuz[4] },
  { number: 5, name: "المائدة", transliteration: "Al-Ma'idah", verses: 120, pages: 16, juz: surahToJuz[6] },
  { number: 6, name: "الأنعام", transliteration: "Al-An'am", verses: 165, pages: 20, juz: surahToJuz[7] },
  { number: 7, name: "الأعراف", transliteration: "Al-A'raf", verses: 206, pages: 24, juz: surahToJuz[8] },
  { number: 8, name: "الأنفال", transliteration: "Al-Anfal", verses: 75, pages: 10, juz: surahToJuz[10] },
  { number: 9, name: "التوبة", transliteration: "At-Tawbah", verses: 129, pages: 12, juz: surahToJuz[10] },
  { number: 10, name: "يونس", transliteration: "Yunus", verses: 109, pages: 11, juz: surahToJuz[11] },
  { number: 11, name: "هود", transliteration: "Hud", verses: 123, pages: 10, juz: surahToJuz[11] },
  { number: 12, name: "يوسف", transliteration: "Yusuf", verses: 111, pages: 12, juz: surahToJuz[12] },
  { number: 13, name: "الرعد", transliteration: "Ar-Ra'd", verses: 43, pages: 6, juz: surahToJuz[13] },
  { number: 14, name: "إبراهيم", transliteration: "Ibrahim", verses: 52, pages: 5, juz: surahToJuz[13] },
  { number: 15, name: "الحجر", transliteration: "Al-Hijr", verses: 99, pages: 6, juz: surahToJuz[14] },
  { number: 16, name: "النحل", transliteration: "An-Nahl", verses: 128, pages: 10, juz: surahToJuz[14] },
  { number: 17, name: "الإسراء", transliteration: "Al-Isra", verses: 111, pages: 11, juz: surahToJuz[15] },
  { number: 18, name: "الكهف", transliteration: "Al-Kahf", verses: 110, pages: 12, juz: surahToJuz[15] },
  { number: 19, name: "مريم", transliteration: "Maryam", verses: 98, pages: 6, juz: surahToJuz[16] },
  { number: 20, name: "طه", transliteration: "Taha", verses: 135, pages: 8, juz: surahToJuz[16] },
  { number: 21, name: "الأنبياء", transliteration: "Al-Anbya", verses: 112, pages: 7, juz: surahToJuz[17] },
  { number: 22, name: "الحج", transliteration: "Al-Hajj", verses: 78, pages: 10, juz: surahToJuz[17] },
  { number: 23, name: "المؤمنون", transliteration: "Al-Mu'minun", verses: 118, pages: 6, juz: surahToJuz[18] },
  { number: 24, name: "النور", transliteration: "An-Nur", verses: 64, pages: 6, juz: surahToJuz[18] },
  { number: 25, name: "الفرقان", transliteration: "Al-Furqan", verses: 77, pages: 6, juz: surahToJuz[19] },
  { number: 26, name: "الشعراء", transliteration: "Ash-Shu'ara", verses: 227, pages: 8, juz: surahToJuz[19] },
  { number: 27, name: "النمل", transliteration: "An-Naml", verses: 93, pages: 7, juz: surahToJuz[20] },
  { number: 28, name: "القصص", transliteration: "Al-Qasas", verses: 88, pages: 8, juz: surahToJuz[20] },
  { number: 29, name: "العنكبوت", transliteration: "Al-'Ankabut", verses: 69, pages: 7, juz: surahToJuz[21] },
  { number: 30, name: "الروم", transliteration: "Ar-Rum", verses: 60, pages: 6, juz: surahToJuz[21] },
  { number: 31, name: "لقمان", transliteration: "Luqman", verses: 34, pages: 3, juz: surahToJuz[21] },
  { number: 32, name: "السجدة", transliteration: "As-Sajdah", verses: 30, pages: 3, juz: surahToJuz[21] },
  { number: 33, name: "الأحزاب", transliteration: "Al-Ahzab", verses: 73, pages: 9, juz: surahToJuz[21] },
  { number: 34, name: "سبإ", transliteration: "Saba", verses: 54, pages: 6, juz: surahToJuz[22] },
  { number: 35, name: "فاطر", transliteration: "Fatir", verses: 45, pages: 5, juz: surahToJuz[22] },
  { number: 36, name: "يس", transliteration: "Ya-Sin", verses: 83, pages: 5, juz: surahToJuz[23] },
  { number: 37, name: "الصافات", transliteration: "As-Saffat", verses: 182, pages: 6, juz: surahToJuz[23] },
  { number: 38, name: "ص", transliteration: "Sad", verses: 88, pages: 5, juz: surahToJuz[23] },
  { number: 39, name: "الزمر", transliteration: "Az-Zumar", verses: 75, pages: 8, juz: surahToJuz[23] },
  { number: 40, name: "غافر", transliteration: "Ghafir", verses: 85, pages: 9, juz: surahToJuz[24] },
  { number: 41, name: "فصلت", transliteration: "Fussilat", verses: 54, pages: 5, juz: surahToJuz[24] },
  { number: 42, name: "الشورى", transliteration: "Ash-Shuraa", verses: 53, pages: 5, juz: surahToJuz[25] },
  { number: 43, name: "الزخرف", transliteration: "Az-Zukhruf", verses: 89, pages: 6, juz: surahToJuz[25] },
  { number: 44, name: "الدخان", transliteration: "Ad-Dukhan", verses: 59, pages: 3, juz: surahToJuz[25] },
  { number: 45, name: "الجاثية", transliteration: "Al-Jathiyah", verses: 37, pages: 3, juz: surahToJuz[25] },
  { number: 46, name: "الأحقاف", transliteration: "Al-Ahqaf", verses: 35, pages: 4, juz: surahToJuz[26] },
  { number: 47, name: "محمد", transliteration: "Muhammad", verses: 38, pages: 4, juz: surahToJuz[26] },
  { number: 48, name: "الفتح", transliteration: "Al-Fath", verses: 29, pages: 4, juz: surahToJuz[26] },
  { number: 49, name: "الحجرات", transliteration: "Al-Hujurat", verses: 18, pages: 2, juz: surahToJuz[26] },
  { number: 50, name: "ق", transliteration: "Qaf", verses: 45, pages: 3, juz: surahToJuz[26] },
  { number: 51, name: "الذاريات", transliteration: "Adh-Dhariyat", verses: 60, pages: 3, juz: surahToJuz[27] },
  { number: 52, name: "الطور", transliteration: "At-Tur", verses: 49, pages: 2, juz: surahToJuz[27] },
  { number: 53, name: "النجم", transliteration: "An-Najm", verses: 62, pages: 2, juz: surahToJuz[27] },
  { number: 54, name: "القمر", transliteration: "Al-Qamar", verses: 55, pages: 3, juz: surahToJuz[27] },
  { number: 55, name: "الرحمن", transliteration: "Ar-Rahman", verses: 78, pages: 3, juz: surahToJuz[27] },
  { number: 56, name: "الواقعة", transliteration: "Al-Waqi'ah", verses: 96, pages: 3, juz: surahToJuz[27] },
  { number: 57, name: "الحديد", transliteration: "Al-Hadid", verses: 29, pages: 3, juz: surahToJuz[27] },
  { number: 58, name: "المجادلة", transliteration: "Al-Mujadila", verses: 22, pages: 2, juz: surahToJuz[28] },
  { number: 59, name: "الحشر", transliteration: "Al-Hashr", verses: 24, pages: 2, juz: surahToJuz[28] },
  { number: 60, name: "الممتحنة", transliteration: "Al-Mumtahanah", verses: 13, pages: 2, juz: surahToJuz[28] },
  { number: 61, name: "الصف", transliteration: "As-Saff", verses: 14, pages: 1, juz: surahToJuz[28] },
  { number: 62, name: "الجمعة", transliteration: "Al-Jumu'ah", verses: 11, pages: 1, juz: surahToJuz[28] },
  { number: 63, name: "المنافقون", transliteration: "Al-Munafiqun", verses: 11, pages: 1, juz: surahToJuz[28] },
  { number: 64, name: "التغابن", transliteration: "At-Taghabun", verses: 18, pages: 1, juz: surahToJuz[28] },
  { number: 65, name: "الطلاق", transliteration: "At-Talaq", verses: 12, pages: 1, juz: surahToJuz[28] },
  { number: 66, name: "التحريم", transliteration: "At-Tahrim", verses: 12, pages: 1, juz: surahToJuz[28] },
  { number: 67, name: "الملك", transliteration: "Al-Mulk", verses: 30, pages: 2, juz: surahToJuz[29] },
  { number: 68, name: "القلم", transliteration: "Al-Qalam", verses: 52, pages: 2, juz: surahToJuz[29] },
  { number: 69, name: "الحاقة", transliteration: "Al-Haqqah", verses: 52, pages: 2, juz: surahToJuz[29] },
  { number: 70, name: "المعارج", transliteration: "Al-Ma'aarij", verses: 44, pages: 1, juz: surahToJuz[29] },
  { number: 71, name: "نوح", transliteration: "Nuh", verses: 28, pages: 1, juz: surahToJuz[29] },
  { number: 72, name: "الجن", transliteration: "Al-Jinn", verses: 28, pages: 1, juz: surahToJuz[29] },
  { number: 73, name: "المزمل", transliteration: "Al-Muzzammil", verses: 20, pages: 1, juz: surahToJuz[29] },
  { number: 74, name: "المدثر", transliteration: "Al-Muddaththir", verses: 56, pages: 1, juz: surahToJuz[29] },
  { number: 75, name: "القيامة", transliteration: "Al-Qiyamah", verses: 40, pages: 1, juz: surahToJuz[29] },
  { number: 76, name: "الإنسان", transliteration: "Al-Insan", verses: 31, pages: 2, juz: surahToJuz[29] },
  { number: 77, name: "المرسلات", transliteration: "Al-Mursalat", verses: 50, pages: 2, juz: surahToJuz[29] },
  { number: 78, name: "النبأ", transliteration: "An-Naba", verses: 40, pages: 1, juz: surahToJuz[30] },
  { number: 79, name: "النازعات", transliteration: "An-Naazi'aat", verses: 46, pages: 2, juz: surahToJuz[30] },
  { number: 80, name: "عبس", transliteration: "Abasa", verses: 42, pages: 1, juz: surahToJuz[30] },
  { number: 81, name: "التكوير", transliteration: "At-Takwir", verses: 29, pages: 1, juz: surahToJuz[30] },
  { number: 82, name: "الإنفطار", transliteration: "Al-Infitaar", verses: 19, pages: 1, juz: surahToJuz[30] },
  { number: 83, name: "المطففين", transliteration: "Al-Mutaffifin", verses: 36, pages: 1, juz: surahToJuz[30] },
  { number: 84, name: "الإنشقاق", transliteration: "Al-Inshiqaaq", verses: 25, pages: 1, juz: surahToJuz[30] },
  { number: 85, name: "البروج", transliteration: "Al-Buruj", verses: 22, pages: 1, juz: surahToJuz[30] },
  { number: 86, name: "الطارق", transliteration: "At-Taariq", verses: 17, pages: 1, juz: surahToJuz[30] },
  { number: 87, name: "الأعلى", transliteration: "Al-A'la", verses: 19, pages: 1, juz: surahToJuz[30] },
  { number: 88, name: "الغاشية", transliteration: "Al-Ghashiyah", verses: 26, pages: 1, juz: surahToJuz[30] },
  { number: 89, name: "الفجر", transliteration: "Al-Fajr", verses: 30, pages: 1, juz: surahToJuz[30] },
  { number: 90, name: "البلد", transliteration: "Al-Balad", verses: 20, pages: 1, juz: surahToJuz[30] },
  { number: 91, name: "الشمس", transliteration: "Ash-Shams", verses: 15, pages: 1, juz: surahToJuz[30] },
  { number: 92, name: "الليل", transliteration: "Al-Layl", verses: 21, pages: 1, juz: surahToJuz[30] },
  { number: 93, name: "الضحى", transliteration: "Ad-Duhaa", verses: 11, pages: 1, juz: surahToJuz[30] },
  { number: 94, name: "الشرح", transliteration: "Ash-Sharh", verses: 8, pages: 1, juz: surahToJuz[30] },
  { number: 95, name: "التين", transliteration: "At-Tin", verses: 8, pages: 1, juz: surahToJuz[30] },
  { number: 96, name: "العلق", transliteration: "Al-Alaq", verses: 19, pages: 1, juz: surahToJuz[30] },
  { number: 97, name: "القدر", transliteration: "Al-Qadr", verses: 5, pages: 1, juz: surahToJuz[30] },
  { number: 98, name: "البينة", transliteration: "Al-Bayyinah", verses: 8, pages: 1, juz: surahToJuz[30] },
  { number: 99, name: "الزلزلة", transliteration: "Az-Zalzalah", verses: 8, pages: 1, juz: surahToJuz[30] },
  { number: 100, name: "العاديات", transliteration: "Al-Aadiyaat", verses: 11, pages: 1, juz: surahToJuz[30] },
  { number: 101, name: "القارعة", transliteration: "Al-Qari'ah", verses: 11, pages: 1, juz: surahToJuz[30] },
  { number: 102, name: "التكاثر", transliteration: "At-Takaathur", verses: 8, pages: 1, juz: surahToJuz[30] },
  { number: 103, name: "العصر", transliteration: "Al-Asr", verses: 3, pages: 1, juz: surahToJuz[30] },
  { number: 104, name: "الهمزة", transliteration: "Al-Humazah", verses: 9, pages: 1, juz: surahToJuz[30] },
  { number: 105, name: "الفيل", transliteration: "Al-Fil", verses: 5, pages: 1, juz: surahToJuz[30] },
  { number: 106, name: "قريش", transliteration: "Quraysh", verses: 4, pages: 1, juz: surahToJuz[30] },
  { number: 107, name: "الماعون", transliteration: "Al-Maa'un", verses: 7, pages: 1, juz: surahToJuz[30] },
  { number: 108, name: "الكوثر", transliteration: "Al-Kawthar", verses: 3, pages: 1, juz: surahToJuz[30] },
  { number: 109, name: "الكافرون", transliteration: "Al-Kafirun", verses: 6, pages: 1, juz: surahToJuz[30] },
  { number: 110, name: "النصر", transliteration: "An-Nasr", verses: 3, pages: 1, juz: surahToJuz[30] },
  { number: 111, name: "المسد", transliteration: "Al-Masad", verses: 5, pages: 1, juz: surahToJuz[30] },
  { number: 112, name: "الإخلاص", transliteration: "Al-Ikhlas", verses: 4, pages: 1, juz: surahToJuz[30] },
  { number: 113, name: "الفلق", transliteration: "Al-Falaq", verses: 5, pages: 1, juz: surahToJuz[30] },
  { number: 114, name: "الناس", transliteration: "An-Naas", verses: 6, pages: 1, juz: surahToJuz[30] },
];
